#!/bin/bash
# Place this in /etc/cron.daily for daily updates
cd /tmp
printf "Updating repo... "
curl -sLJO https://github.com/iptv-org/iptv/raw/master/channels/us.m3u
curl -sLJO https://github.com/iptv-org/iptv/raw/master/channels/uk.m3u
printf "done!\nMerging lists... "
cat us.m3u uk.m3u >eng.m3u
# Remove header from second file and sanitize content
L2=$(awk '/EXTM3U/ {if(NR !=1) print NR}' eng.m3u)
sed -i "s/^#EXTM3U.*/#EXTM3U/; ${L2}d; /XXX/ {N; d;}" eng.m3u
mv eng.m3u /var/www/iptv/stream/ && rm *.m3u
echo "done!"
